---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "vkr1998/docker_jenkins_springboot:15"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
